CREATE TABLE "tennisaddicts_listings" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "tennisaddicts_listings_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" varchar(256) NOT NULL,
	"title" varchar(256) NOT NULL,
	"description" varchar(1024) NOT NULL,
	"price" numeric(10, 2) DEFAULT '0' NOT NULL,
	"location" jsonb NOT NULL,
	"tags" varchar(256)[],
	"images" jsonb NOT NULL,
	"status" varchar(50) DEFAULT 'active' NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE INDEX "title_idx" ON "tennisaddicts_listings" USING btree ("title");--> statement-breakpoint
CREATE INDEX "user_id_idx" ON "tennisaddicts_listings" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "location_idx" ON "tennisaddicts_listings" USING btree ("location");--> statement-breakpoint
CREATE INDEX "status_idx" ON "tennisaddicts_listings" USING btree ("status");