import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "@/components/ui/sonner";
import { ErrorBoundary } from "./components/ErrorBoundary";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Tennis Addicts",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased flex h-screen overflow-hidden`}
        >
          <ErrorBoundary>
            <SidebarProvider>
              <div className="flex w-full h-full">
                <AppSidebar className="flex-shrink-0" />
                <main className="flex-1 overflow-auto">
                  {children}
                  {modal}
                  <div id="modal-root" />
                  <Toaster />
                </main>
              </div>
            </SidebarProvider>
          </ErrorBoundary>
        </body>
      </html>
    </ClerkProvider>
  );
}
